spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secure_auth_service
    username: postgres
    password: postgres@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: Q8xQ9IOU9Clvonifj0eaGzAfUiUwOevFCuj6O4wMpuGDfJFY0pR3XJXcsnPJuxi5rKZ06FaNY42HcSpt5A1owA==
  expiration: 900000
server:
  port: 8081